### ISSUE TITLE
Fuzz tests hanging on Windows

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/node-test-runner#53]
Travis is fine, but AppVeyor hangs. No idea what the problem might be.

https://ci.appveyor.com/project/rtfeldman/node-test-runner/build/job/f985x4rif8t3tad9

It just stops printing output here:

![screen shot 2016-08-10 at 9 36 01 am](https://cloud.githubusercontent.com/assets/1094080/17562094/038ca988-5ede-11e6-997f-7800f508b269.png)

**Comment by bdukes** [comment]
On my windows box, included a fuzz test causes both the node and html runners to hang.  I'll see if I can track down where that's happening.

**Comment by bdukes** [comment]
A quick debug session shows what looks like an infinite loop in a function named `accountForBias`.  The passed in `seed` is an object that looks like `{ _0: 0, _1: 0, ctor: "Seed" }`, as is `seedN`, and `x` (the result from calling `_mgold$elm_random_pcg$Random_Pcg$peel(seed)`) is always `0`.  `if (_elm_lang$core$Native_Utils.cmp(x, threshhold) < 0)` is always `true`, so it gets stuck in that loop.

Here is that JS code, with some context:

```
var _mgold$elm_random_pcg$Random_Pcg$int = F2(
	function (a, b) {
		return _mgold$elm_random_pcg$Random_Pcg$Generator(
			function (seed0) {
				var _p64 = (_elm_lang$core$Native_Utils.cmp(a, b) < 0) ? {ctor: '_Tuple2', _0: a, _1: b} : {ctor: '_Tuple2', _0: b, _1: a};
				var lo = _p64._0;
				var hi = _p64._1;
				var range = (hi - lo) + 1;
				if (_elm_lang$core$Native_Utils.eq(
					A2(_elm_lang$core$Bitwise$and, range, range - 1),
					0)) {
					return {
						ctor: '_Tuple2',
						_0: A2(
							_elm_lang$core$Bitwise$shiftRightLogical,
							A2(
								_elm_lang$core$Bitwise$and,
								_mgold$elm_random_pcg$Random_Pcg$peel(seed0),
								range - 1),
							0),
						_1: _mgold$elm_random_pcg$Random_Pcg$next(seed0)
					};
				} else {
					var threshhold = A2(
						_elm_lang$core$Bitwise$shiftRightLogical,
						A2(
							_elm_lang$core$Basics$rem,
							A2(_elm_lang$core$Bitwise$shiftRightLogical, 0 - range, 0),
							range),
						0);
					var accountForBias = function (seed) {
						accountForBias:
						while (true) {
							var seedN = _mgold$elm_random_pcg$Random_Pcg$next(seed);
							var x = _mgold$elm_random_pcg$Random_Pcg$peel(seed);
							if (_elm_lang$core$Native_Utils.cmp(x, threshhold) < 0) {
								var _v26 = seedN;
								seed = _v26;
								continue accountForBias;
							} else {
								return {
									ctor: '_Tuple2',
									_0: A2(_elm_lang$core$Basics$rem, x, range) + lo,
									_1: seedN
								};
							}
						}
					};
					return accountForBias(seed0);
				}
			});
	});
```

Note that, even though the first line here ends with `int`, that this occurs just the same when using `Fuzz.string`.

**Comment by rtfeldman** [comment]
Wow, crazy! @mgold thoughts?

**Comment by NicolasUmiastowski** [comment]
Hi, I have a unit test suite that runs nice, but when I add a fuzz test, and want to run the page on localhost, on windows, it fails to lad, something seems to loop indefinitely, preventign the page form loading. It also provokes the console to stop there, I can do nothing after lauching the tests. 
Here is the code, the problematic is the last one (a fuzz test)


`module HtmlRunnerExample exposing (..)

{-| HOW TO RUN THIS EXAMPLE

$ elm-reactor

Visit http://localhost:8000 and bring up this file.
-}


import Expect
import Test exposing (..)
import Test.Runner.Html
--import Fuzz exposing (..)

import Preprojectform exposing (..)
import Dict exposing (..)

import Fuzz exposing (list, int, tuple,intRange)

main : Program Never
main =
    [ all
    ]
        |> concat
        |> Test.Runner.Html.run

all : Test
all =
    describe "A Test Suite"
        [ test "Addition" <|
            \() ->
                Expect.equal (3 + 7) 10
        {-, test "This test should fail" <|
            \() ->
                Expect.fail "failed as expected!"-}
       
        , test "Length of listOfQuestions" <|
                \() ->
                    (fst Preprojectform.init).listOfQuestions
                        |> List.length
                        |> Expect.equal 2

        , test "Value of maxPointsPossible" <|
                \() ->
                    (fst Preprojectform.init).listOfQuestions
                        |> List.length
                        |> (*) 3
                        |> Expect.equal 6

        {-, test "My current number of points" <|
                \() ->
                    (List.sum <| Dict.values <| (fst Preprojectform.init).myScoreList)
                        |> Expect.greaterThan 0   -}
         
        {-, test "My current number of points" <|
                \() ->
                    let 
                        myScore =  
                            (fst Preprojectform.init).myScoreList
                        myCurrentNumberofPoints =  
                            List.sum <| Dict.values <| myScore
                    in
                         if isEmpty myScore then
                                myCurrentNumberofPoints |> Expect.equal 0   
                         else 
                                myCurrentNumberofPoints |> Expect.greaterThan 0-}

        , test "My scoreList" <|
                \() ->
                      (fst Preprojectform.init)
                         |> Preprojectform.update (Preprojectform.QuestionAnswered  1 3)
                         |> fst
                         |> Preprojectform.update (Preprojectform.QuestionAnswered  2 3)
                         |> fst
                         |> .myScoreList
                         |> Expect.equal  (Dict.fromList [(1,3), (2,3)])

     
        , test "My current number of points" <|
                \() ->
                      (fst Preprojectform.init)
                         |> Preprojectform.update (Preprojectform.QuestionAnswered  1 3)
                         |> fst
                         |> Preprojectform.update (Preprojectform.QuestionAnswered  2 3)
                         |> fst
                         |> Preprojectform.update (Preprojectform.Send 100)
                         |> fst
                         |> .scoreMessage
                         |> Expect.equal  "Your score is 100% Bravo"

       

       , fuzz (intRange 1 50) "Fuzz test for Integer" <|
            \myInt ->
                (myInt * 200) // 5
                      |> Expect.greaterThan 2000 
        
        ]
`

**Comment by mgold** [comment]
The test works (fails as expected) on a Mac, which is the only machine I have access to. Very strange!

@bdukes Can you provide minimal Elm code that reproduces the issue you are seeing? `Seed 0 0` should not be possible!

**Comment by NicolasUmiastowski** [comment]
@mgold  , @rtfeldman ldman : 
OK I re-tried and I can confirm you that : 
actually it fails ONLY when I have the whole code above (unit tests + the fuzz test - even if the fuzz test is the last or the first or at another place)
When I keep only the fuzz test in the code, it works (both in the console and also in localhost when I add it to HtmlRunnerExample.elm)  : 

`module Tests exposing (..)

import Test exposing (..)
import Expect
--import Dict exposing (..)
import Fuzz exposing (list, int, tuple,intRange)

import Preprojectform exposing (..)
import Dict exposing (..)


all : Test
all =
    describe "A Test Suite"
        [ fuzz (intRange -1 -50) "Fuzz test for Integer" <|
            \myInt ->
                (myInt * 200) // 5
                      |> Expect.greaterThan 2000 
        ]`

**Comment by NicolasUmiastowski** [comment]
@mgold  , @rtfeldman : 
This one is the smallest that fails : 
```elm
module HtmlRunnerExample exposing (..)

{-| HOW TO RUN THIS EXAMPLE ?

************************* WARNING !!!!!!!  $ elm-reactor should be run from the tests directory !!!!*********************

Visit http://localhost:8000 and bring up this file.
-}


import Expect
import Test exposing (..)
import Test.Runner.Html
--import Fuzz exposing (..)

import Preprojectform exposing (..)
import Dict exposing (..)

import Fuzz exposing (list, int, tuple,intRange)

main : Program Never
main =
    [ all
    ]
        |> concat
        |> Test.Runner.Html.run

all : Test
all =
    describe "A Test Suite"
        [ test "My current number of points" <|
                \() ->
                    (List.sum <| Dict.values <| (fst Preprojectform.init).myScoreList)
                        |> Expect.greaterThan 0
         
        , fuzz (intRange 1 50) "Fuzz test for Integer" <|
            \myInt ->
                (myInt * 200) // 5
                      |> Expect.greaterThan 2000
        
        ]```

**Comment by NicolasUmiastowski** [comment]
I finally think it has something to do with whitespaces, empty lines or something like this becuase this one below (where I deleteted some empty lines between the tests) works fine : 

```elm
module HtmlRunnerExample exposing (..)

 

{-| HOW TO RUN THIS EXAMPLE ?

 

************************* WARNING !!!!!!!  $ elm-reactor should be run from the tests directory !!!!*********************

 

Visit http://localhost:8000 and bring up this file.

-}

 

 

import Expect

import Test exposing (..)

import Test.Runner.Html

--import Fuzz exposing (..)

 

import Preprojectform exposing (..)

import Dict exposing (..)

 

import Fuzz exposing (list, int, tuple,intRange)

 

main : Program Never

main =

    [ all

    ]

        |> concat

        |> Test.Runner.Html.run

 

all : Test

all =

    describe "A Test Suite"

        [ test "One addition" <|

            \() ->

                Expect.equal (3 + 7) 10

         , test "My current number of points" <|

                \() ->

                      (fst Preprojectform.init)

                         |> Preprojectform.update (Preprojectform.QuestionAnswered  1 3)

                         |> fst

                         |> Preprojectform.update (Preprojectform.QuestionAnswered  2 3)

                         |> fst

                         |> Preprojectform.update (Preprojectform.Send 100)

                         |> fst

                         |> .scoreMessage

                         |> Expect.equal  "Your score is 100% Bravo"

         , fuzz (intRange 1 50) "Fuzz test for Integer" <|

            \myInt ->

                (myInt * 200) // 5

                      |> Expect.greaterThan 2000

        

        ]

```

**Comment by bdukes** [comment]
It seems that it's less common an issue when there's only one fuzz test.  I'm not able to reproduce the issue with just one fuzz test all by itself, but adding another test (fuzz or regular) before the fuzz test seems to cause it to happen (adding a test _after_ the fuzz test did _not_ seem to trigger the hang).  It hangs regardless of whether either test passes or fails.

This causes a hang about 4 in 5 times:
```
port module Main exposing (..)

import Test.Runner.Node exposing (run)
import Json.Encode exposing (Value)
import Expect
import Test exposing (..)
import Fuzz exposing (list, int, tuple, intRange)

all : Test
all =
    describe "A Test Suite"
        [ fuzz (list int) "List length" <|
            \numbers ->
                List.length (List.reverse numbers)
                    |> Expect.equal (List.length numbers)
        , fuzz (intRange 1 50) "Fuzz test for Integer" <|
            \myInt ->
                (myInt * 200) // 5
                      |> Expect.greaterThan 20
        ]

main : Program Never
main =
    run emit all


port emit : ( String, Value ) -> Cmd msg
```

This causes a hang about 1 in 10 times:
```
port module Main exposing (..)

import Test.Runner.Node exposing (run)
import Json.Encode exposing (Value)
import Expect
import Test exposing (..)
import Fuzz exposing (list, int, tuple, intRange)

all : Test
all =
    describe "A Test Suite"
        [ test "List length" <|
            \() ->
                List.length (List.reverse [1, 2, 3])
                    |> Expect.equal 3
        , fuzz (intRange 1 50) "Fuzz test for Integer" <|
            \myInt ->
                (myInt * 200) // 5
                      |> Expect.greaterThan 20
        ]

main : Program Never
main =
    run emit all


port emit : ( String, Value ) -> Cmd msg
```

**Comment by mgold** [comment]
Okay, so after trying a variation of @NicolasUmiastowski's "smallest one that fails" (variation because  I don't have the `Preprojectform` source), I was able to see some hanging behavior on Mac/Chrome. I noticed that Chrome reported "Waiting on fonts.googleapis.com", which on further investigation appears to be GET http://fonts.googleapis.com/css?family=Source+Sans+Pro, which comes from an `@import` in a `<style>` in `<head>`. So if this is indeed the cause of the hangs you've been seeing, it has nothing to do with elm-test. (The import should be removed from the reactor because the body text is done properly: `font-family: monospace` which picks up system Courier.)

If you run `elm make HtmlRunnerExample.elm` the `@import` will not be present in `index.html`. Try loading that file repeatedly and see if you can produce a hang.

**Comment by bdukes** [comment]
@mgold I'm seeing the hanging (on Windows) using the `elm-test` command line utility, not just in `elm-reactor`.

**Comment by NicolasUmiastowski** [comment]
Same for me. 
And just to make it clear, I jut want to help here.
Here is the code of Preprojectform.elm 

```elm
module Preprojectform exposing (Model,init,view,update,Msg(..))

import Html exposing (..)
import Html.Attributes exposing (..)
import Html.App as Html
import Html.Events exposing (onClick, onCheck)
import Dict exposing (..)
import Debug
-- import Debug




main : Program Never
main =
  Html.program
    { init = init
    , view = view
    , subscriptions = subscriptions
    , update = update
    }


  -- MODEL


type alias Model =
  { myScoreList : Dict Int Int
    ,listOfAnswers : List { myText: String, myValue: Int}
    ,listOfQuestions : List { questionId: Int, questionText : String }
    ,scoreMessage : String
    ,errrorMessage : String
  }
 

init :  (Model, Cmd Msg)
init =
  (Model Dict.empty [{myText = "Fully agree", myValue = 3}, {myText = "Agree", myValue = 2}, {myText = "Neutral", myValue = 1}, {myText = "Disagree", myValue=0}]  [{questionId = 1, questionText = "Is the business co-located with the developers?"}, {questionId = 2, questionText = "Is the scope flexible?"}] "" "", Cmd.none)

--MESSAGES
type Msg = 
    QuestionAnswered Int Int
    | Send Int

--VIEW
view
    : Model
    -> Html Msg

view model =
  let
    displayListOfQuestions = List.concatMap  (\question ->  text question.questionText :: List.map (createAnswerButtons question.questionId) model.listOfAnswers) model.listOfQuestions
    
    maxPointsPossible : Int
    maxPointsPossible = List.length model.listOfQuestions * 3

    myCurrentNumberofPoints = List.sum <| Dict.values <| model.myScoreList
    
    myTotalScore : Int
    myTotalScore = (myCurrentNumberofPoints * 100) // maxPointsPossible
    
    
  in
    div []
    <|displayListOfQuestions ++
      [ br [] []
      , button [onClick (Send myTotalScore) ] [text "Send"]
      , br [] []
      , br [] []
      , text model.scoreMessage
      , text model.errrorMessage
      ] 

createAnswerButtons : Int -> { a | myText : String, myValue : Int } -> Html Msg
createAnswerButtons questionId answersPair = 
    div[]
    [ text (answersPair.myText)
    , input [ type' "radio", name ("myChoice" ++ toString questionId), onCheck (\_ -> QuestionAnswered questionId answersPair.myValue)] []
    ]
--UPDATE
update
    : Msg
    -> Model
    -> ( Model, Cmd b)

update msg model = 
    case msg of 
        QuestionAnswered  questionId answersId ->
          let 
            newScoreList = Dict.insert questionId answersId model.myScoreList
     
          in 
          ({ model |  myScoreList = Debug.log "myscorelist" newScoreList }, Cmd.none )
        Send myTotalScore ->
            let 
            myAnsweredQuestions = List.length <| Dict.values <| model.myScoreList
            newScoreMessage =
                if  (myAnsweredQuestions == 2 && myTotalScore  >= 75) then 
                    "Your score is " ++ toString myTotalScore ++ "% " ++ "Bravo"
                else 
                    if (myAnsweredQuestions == 2 && myTotalScore  < 75) then
                     "Your score is " ++ toString myTotalScore ++ "% " ++  "Not so bad"
                else ""
            newErrorMessage = 
                if ((List.length <| Dict.values <| model.myScoreList) < 2) then
                    "You must answer all questions!"
                else
                    ""
            in 
            ({ model | scoreMessage = newScoreMessage , errrorMessage = newErrorMessage }, Cmd.none )


--SUBSCRIPTIONS
subscriptions : Model -> Sub Msg
subscriptions model = 
    Sub.none


`

**Comment by mgold** [comment]
Nicholas, sorry for the snarky comment. I'm at the SF meetup now, and apparently someone repo'd it on OS X, so we'll dig in shortly.

Also Evan says he's moved the CSS import to the bottom of the file, on master.

**Comment by rtfeldman** [comment]
Has anyone been able to reproduce this on any other platform than Windows?

**Comment by rtfeldman** [comment]
I just published a new version of `node-test-runner` (get it by upgrading your `elm-package.json` to say `"rtfeldman/node-test-runner": "2.0.1 <= v < 3.0.0"` and by also running `npm install -g elm-test`) - and it now prints out a seed at the start of each test run.

@NicolasUmiastowski @bdukes would you mind upgrading to the latest version, re-running, and then pasting in the `--seed` argument to reproduce? It should look something like this:

<img width="768" alt="screen shot 2016-08-17 at 9 53 13 pm" src="https://cloud.githubusercontent.com/assets/1094080/17792650/fd65aea4-6556-11e6-82ed-b2489e7eafcd.png">

If you can paste me that "To reproduce these results" line, I can try to reproduce locally.

Thanks!

**Comment by NicolasUmiastowski** [comment]
Wow it works now with the fuzz test :)
here is the line : 
To reproduce these results,  run: elm-test --seed 921421987

coool!

**Comment by rtfeldman** [comment]
@NicolasUmiastowski ok cool! So the next time it hangs, can you paste this again? (The number will be different next time, since it is randomly generated at the start of each run.)

This will help me reproduce it. If I have that seed number and your code, I can re-run the exact tests on my machine, and all the fuzz values will be the same as the ones that you had. 😄

**Comment by NicolasUmiastowski** [comment]
ok cool. but as it works now, it will hopefully not fail again :)
let's see :)

**Comment by bdukes** [comment]
I'm still seeing hanging.  

Seeds that hang include:
- 2082731988
- 1486799622
- 478853078
- 1443275616
- 494046381

Seeds that complete include:
- 1125685972
- 1854048834
- 422094152
- 951047110
- 1679977496

Hope it helps!

**Comment by rtfeldman** [comment]
@bdukes ok cool! can you link to the code that reproduces the hanging with these seeds?

**Comment by bdukes** [comment]
The code is https://gist.github.com/bdukes/37df29534fc83ca56c1292f61f26d3d3

**Comment by mgold** [comment]
Hey @bdukes, I downloaded the zip from the gist, ran `npm update -g elm-test`, and then in the gist folder ran `elm test Main.elm --seed=2082731988` for each of the seeds you list as hanging, and was unable to reproduce the hang. That is, the suite completed (with two failed tests) almost instantly every time. Have you tried running each of the hanging seeds a times each to confirm that they always cause a hang? Have you tried running the non-hanging seeds a few times each to confirm they never hang? (Sorry if this sounds like nagging!)

**Comment by bdukes** [comment]
@mgold, no problem, I hadn't actually tried re-running any of those seeds to verify whether they consistently caused a hang or not.  Now that I have, it does seem consistent.  I can run `elm-test --seed=1854048834` 20 times without a hang, and `elm-test --seed 1486799622` has hung five times in a row.

Hope it helps!

**Comment by rtfeldman** [comment]
And this is only hanging on Windows, yeah?

**Comment by bdukes** [comment]
Correct, I'm only on Windows.

**Comment by rtfeldman** [comment]
Got it. Out of curiosity, can you reproduce this in the html test runner on Chrome, Firefox, and IE (or Edge)?

I ask because the node test runner would be using v8 under the hood just like Chrome, so I wonder if the bug might be specific to v8 on windows.

**Comment by bdukes** [comment]
​Yes, I can reproduce in Firefox and Edge.​

**Comment by benansell** [comment]
Thanks to the test case from @bdukes I was able to put together a small repo that runs the test case with the "good seeds" (test fails without hanging) and "hang seeds". 

The travis build (linux) runs fine, however the appveyor (windows) build fails every time on the 1486799622 seed regardless which version of nodejs is being used.

I have also added some debug lines to the output to see if it was possible to record it getting stuck - sadly that didn't work. However, it does show that the linux and windows builds are getting different "seed" values in the when running the "good seed" tests (unless I am miss reading the output):

```elm
all : Test
all =
    describe "A Test Suite"
        [ test "Addition" <|
            \() ->
                Expect.equal (3 + 7) 10
                    |> Debug.log "--------- Addition test complete ---------"
        , fuzz Fuzz.int "variable addition" <|
            \a ->
                Expect.equal (3 + a + 2) (a + 6)
                    |> Debug.log (toString a)
        , test "This test should fail" <|
            \() ->
                Expect.fail "failed as expected!"
                    |> Debug.log "--------- Failed test complete ---------"
        ]
```


[travis - line 426](https://travis-ci.org/benansell/node-test-runner-issue-53-test):
```
elm-test
--------
Running 3 tests. To reproduce these results, run: elm-test --seed 1125685972
--------- Addition test complete ---------: Pass
42: Fail "" "48\n╷\n│ Expect.equal\n╵\n47"
0: Fail "" "6\n╷\n│ Expect.equal\n╵\n5"
0: Fail "" "6\n╷\n│ Expect.equal\n╵\n5"
10: Fail "" "16\n╷\n│ Expect.equal\n╵\n15"
```

[appveyor - line 164](https://ci.appveyor.com/project/benansell/node-test-runner-issue-53-test):
```
elm-test
--------
Running 3 tests. To reproduce these results, run: elm-test --seed 1125685972
--------- Addition test complete ---------: Pass
-1682754193: Fail "" "-1682754187\n╷\n│ Expect.equal\n╵\n-1682754188"
1682754193: Fail "" "1682754199\n╷\n│ Expect.equal\n╵\n1682754198"
0: Fail "" "6\n╷\n│ Expect.equal\n╵\n5"
0: Fail "" "6\n╷\n│ Expect.equal\n╵\n5
```

**Comment by mgold** [comment]
Hmm, it's pretty clear that there's some kind of windows or windows-version-of-JS-engine bug involving arithmetic or bitwise ops. I'm really not sure what to do about it.

Looking at that output did illustrate another point. Notice there are lots of zeros; this is due to shrinking. It's expected that a test may be rerun many times as values are shrunk but zero always appears twice. Turns out we we calling the test once more than we needed at the very end. Not doing that improved performance about 5-10% when shrinking tuples (which can do a lot of shrink steps, so to get perf out of saving only one is a pleasant surprise). This ought to make it into 2.1.0.

But back on topic, yeah, I have no idea. :(

**Comment by mgold** [comment]
@bdukes @NicolasUmiastowski Please delete `tests/elm-stuff` and run `elm test` with a broken seed to redownload. Can you reproduce the issue still? If not, mgold/elm-random-pcg#11 probably fixed it.

**Comment by bdukes** [comment]
@mgold, yes that appears to have fixed it!  Great job!

**Comment by rtfeldman** [comment]
Nice!!!

**Comment by NicolasUmiastowski** [comment]
@mgold : yes for me too the hanging problem disappeared!
That's great. 
Thanks a lot, and have a good beer :)

**Comment by mgold** [comment]
Great! And buy the 🍺 for @ianmackenzie!

@rtfeldman I think you can close the issue. 🎉 😃

**Comment by rtfeldman** [comment]
Just wanted to say, extra huge props to @mgold for fixing this and to @bdukes @benansell @NicolasUmiastowski for your hard work reproducing it.

Great work all around!
